config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 
 
  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end
  
  def create
      @task = current_user.tasks.new(task_params)
      if @task.save
           # #20
      respond_to do |format|
         format.html {redirect_to root_path}
         format.js
       flash[:notice] = "Task was saved successfully."
      end
      else
       flash.now[:alert] = "Error creating task. Please try again."
       render :new
      end
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "Task updated"
    else
      flash[:alert] = 'Error creating task. Please try again'
    end
    redirect_to root_path
  end
 
  def destroy 
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:notice] = "Task Removed"
      redirect_to root_path
    else
      flash[:alert] = "Task not removed"
      render :show
    end
  end
 
 
  private
  
  def task_params
      params.require(:task).permit(:body, :completed)
  end 



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
    
    
 def time_remaining_for(task_timestamp)
   days_left = (7 - (Date.today - task_timestamp.to_date)).to_i
   "#{days_left} days"
 end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
 <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 <% flash.each do |key, value| %>
     <div class = "alert alert-<%=key %>"><%=value%></div>
 <% end %>
<div class="container">
  <%= yield %>   
 </div>

</body>
</html>

app/views/tasks/_form.html.erb
 <%= form_for @task, remote: true  do |f| %>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Description" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/tasks/_task.html.erb
<div class="media">
 <div class="media-body">
   <h4 class="media-heading">
     <h2>  <%= task.body %> </h2>
     <h4>Time remaining <%= time_remaining_for(task.created_at) %>   </h4>
     
       <%= form_for task do |f| %>
         <%= f.check_box :completed, onchange: 'this.form.submit()' %>
         <%= f.label :completed %>
       <%end%>
       <%= link_to "Delete Task", task, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this task?' } %>
   </h4>
 </div>
</div>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('.tasks').append('<%= j render(@task)%>');

app/views/tasks/index.html.erb
 <h1>Tasks</h1>

<div class="row">
 <div class="col-md-8">
   <%= link_to 'Add Task', new_task_path, id: "new_link", remote: true %>
   <div class="tasks">
    <%= render @tasks%>
   </div>
 </div>
</div>

app/views/tasks/new.html.erb
 <%= form_for @task do, remote: true |f| %>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Description" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/tasks/new.js.erb
$('#new_link').hide().after("<%= j render("form") %>");

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>